// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfSi9SU85OCsC1vICzonfx80AXnYygArQ',
    appId: '1:119085502858:web:19164f3f2863f3d97fb873',
    messagingSenderId: '119085502858',
    projectId: 'ebook-f56e8',
    authDomain: 'ebook-f56e8.firebaseapp.com',
    storageBucket: 'ebook-f56e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBerDEoY1bDXdysRSWpkYJewwCoPKLMfME',
    appId: '1:119085502858:android:e244ed15d80e89367fb873',
    messagingSenderId: '119085502858',
    projectId: 'ebook-f56e8',
    storageBucket: 'ebook-f56e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0lt03tXd4GDv66U_jGpb_3-qQ4myLtiY',
    appId: '1:119085502858:ios:3705cb32dfb739f47fb873',
    messagingSenderId: '119085502858',
    projectId: 'ebook-f56e8',
    storageBucket: 'ebook-f56e8.appspot.com',
    iosBundleId: 'com.example.ebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0lt03tXd4GDv66U_jGpb_3-qQ4myLtiY',
    appId: '1:119085502858:ios:c231723dc7bc2eda7fb873',
    messagingSenderId: '119085502858',
    projectId: 'ebook-f56e8',
    storageBucket: 'ebook-f56e8.appspot.com',
    iosBundleId: 'com.example.ebook.RunnerTests',
  );
}
